name: firebasetrain2
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  go_router: ^9.0.3
  custom_navigation_bar: ^0.8.2
  auto_size_text: ^3.0.0
  flutter_gradients_reborn: ^1.0.0+7
  shared_preferences: ^2.0.7
  flutter_custom_clippers: ^2.1.0
  basic_utils: ^5.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/log.png
    - assets/img/note_bottom.png
    - assets/img/home_bottom.png
    - assets/img/profile_bottom.png
    - assets/img/create_note_bottom.png
    - assets/img/cat.png
    - assets/img/cat_main.png
    - assets/img/cat_notData.png
    - assets/img/cat_profile.png
    - assets/img/toDo_list.png
    - assets/img/cat_toDo.png

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-Regular.ttf
